services:
  - type: web
    name: datanetra-ai
    env: python
    plan: starter
    pythonVersion: "3.11.0"
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GRADIO_ANALYTICS_ENABLED
        value: "False"
      - key: PORT
        value: "10000"
      - key: PYTHON_VERSION
        value: "3.11.0"
